import VersoSlides
import VersoBlueprint.Graft
import VersoBlueprint.Slides
import Verso.Doc.Concrete
import Lib.Widgets

open VersoSlides

set_option verso.code.warnLineLength 100

#doc (Slides) "Verso Blueprints" =>

# Verso Blueprints

[Emilio Jesús Gallego Arias](https://x80.org/emilio)

Senior Research Engineer — Lean FRO

MadLean Seminar @ UCM Mathematics Department

Wednesday, May 27, 2026

# AI Is Making A Huge Impact On Mathematics

%%%
vertical := some true
%%%

:::hstack

- AI systems are producing mathematics that specialists take *seriously*.
- Mathematicians need ways to _inspect_, _guide_, and _trust_ the process.
- _Mathematical output_ is no longer just a paper or a Lean file.
- A great challenge to mathematics and computer science.

{image "static/images/slide_1.1_erdos.png"}[Erdos' Unit Problem Solution Tweet by Timothy Gowers]

:::

*Timothy Gowers*:

> "If you are a mathematician, then you may want to make sure you are sitting down before reading further."

## DeepMind: 9 Erdos Problems Solved In Collaboration With Lean

:::::vstack

::::hstack

:::arxiv "2605.22763v1" (title := "Advancing Mathematics Research with AI-Driven Formal Proof Search") (authors := "Tsoukalas et al.") (published := "Submitted May 21, 2026")
The paper reports AI-driven formal proof search over open Erdos problems and
OEIS conjectures, using Lean verification as the guardrail.
:::

{image "static/images/slide_2.2_deepmind.png"}[DeepMind Erdos solution]
::::

*Days-old* DeepMind formal-proof-search result makes *Lean* and *Mathlib* central to the proving loop.
:::::

## Sphere Packing Milestone

::::vstack

{arxiv "2604.23468" (title := "A Milestone in Formalization: The Sphere Packing Problem in Dimension 8") (authors := "Hariharan, Birkbeck, Lee, Ma, Mehta, Poiroux, Viazovska") (published := "Submitted Apr 25, 2026; v2 Apr 28, 2026") (summary := "The dimension-8 sphere-packing result was formally verified in February 2026, with final stages carried out by Math Inc.'s Gauss model.")}

:::center
{image "static/images/math_inc_2.png"}[Math Inc Announcement]
:::

::::

## Sphere Packing Blueprint

::::vstack

- The project had a detailed mathematical plan.
- The plan exposed statements, dependencies, and progress.
- Humans and agents needed to know where a proof belonged.
- Systems such as Gauss, Aristotle, Numina, and others need project structure.

::: hstack

{image (width := "95%") "static/images/sp_index.png"}[Sphere-packing blueprint start page]

{image (width := "95%") "static/images/sp_graph.png"}[Sphere-packing blueprint graph]

:::
::::

## What These Milestones Reveal

*The bottleneck has moved.*

It is not only:

- can a theorem be proved in Lean?

It is also:

- can we use AI to jointly build a detailed formalization plan?
- can humans understand the proofs produced by agents?
- can project state be *reviewed*, *maintained*, and *trusted*?

# Blueprint: Historical Context

%%%
vertical := some true
%%%

:::::vstack

- *Feit-Thompson Theorem (~2010)*: Custom system to track progress, generated by CI
- *Flyspeck (~2010)*: _Mathwiki_

*Coordination was part of the mathematics*

*Formalization progress was non-linear*

:::hal "hal-00816699" (title := "A Machine-Checked Proof of the Odd Order Theorem") (authors := "Gonthier, Asperti, Avigad, Bertot, Cohen, Garillot, Le Roux, Mahboubi, O'Connor, Ould Biha, Pasca, Rideau, Solovyev, Tassi, Thery") (published := "Submitted to HAL Apr 22, 2013") (venue := "ITP 2013, LNCS 7998, pp. 163-179") (url := "https://hal.inria.fr/hal-00816699") (pdf := "https://www.msr-inria.fr/files/hal-00816699/file/main.pdf")
The paper reports the machine-checked formal proof of the Feit-Thompson Odd
Order Theorem in Coq/Rocq, built on the Mathematical Components library.
:::

:::::

## LeanBlueprint

::::hstack

- Introduced for the Liquid Tensor Experiment by Patrick Massot and
  collaborators (~2020)
- A LaTeX/plasTeX extension for formalization projects.
- Adds *dependency information*, *graph rendering*, and *formalization status*.
- Widely reused across Lean projects.

:::vstack

{image "static/images/lte1.png"}[Liquid Tensor blueprint screenshot]

{image "static/images/lte2.png"}[Liquid Tensor blueprint screenshot]

:::

::::

## LeanBlueprint: Success And Limits

:::::vstack
::::hstack
:::vstack

*Blueprints are coordination infrastructure*:

- mathematicians read the project map
- formalizers choose tasks from it
- maintainers track progress and blockers
- collaborators discuss the same labeled objects
:::

:::vstack
*LeanBlueprint is very successful, but the requirements are changing*:

- plasTeX is hard to extend and maintain
- synchronization with Lean is manual
- the stack depends on Python and TeX tooling
- TeX is not ideal for machine-to-machine project state
- agents need structured, checked inputs and outputs
:::
::::

{arxiv "2601.22554" (title := "LeanArchitect: Automating Blueprint Generation for Humans and AI") (authors := "Thomas Zhu, Pietro Monticone, Jeremy Avigad, Sean Welleck") (published := "Submitted Jan 30, 2026")}

:::::

# Verso Blueprint

%%%
vertical := some true
%%%

[https://github.com/leanprover/verso-blueprint](https://github.com/leanprover/verso-blueprint)

:::hstack

- Directly inspired by LeanBlueprint, LeanArchitect, and Side to Side
- *Core model in Lean*: labels, nodes, metadata, code links, status
- *Document layer in Verso*: rich, extensible markup and interactive output
- Same data feeds graphs, summaries, previews, slides, and tools

{image (width := "96%") "static/images/vbp-architecture.svg"}[Verso Blueprints architecture diagram]

:::

## Blueprint Data Model

:::::hstack

:::vstack

- globally stable label
- informal statement and proof facets
- dependencies and reverse dependencies
- parent group, owner, tags, priority, effort
- one-to-many code relationships
- Lean declarations, inline code, and other source witnesses

:::

::::attr (style := "flex: 1.35 1 0; align-self: stretch;")
:::vstack

```
Informal.Data
  labels  : LabelMap Node
  groups  : LabelMap Group
  authors : AuthorMap Author
  sources : SourceMap Source

Node(label)
  identity
    global label
    parent? / group?

  mathematical facets
    statement?
    proof?
    source witnesses

  project metadata
    owner? tags priority effort
    uses / used-by

  formal attachments
    Lean declarations
    inline Lean / Rust blocks
    status and preview keys
```

:::
::::

:::::

## Verso Primer

Verso is the *official Lean documentation and markup system*:

1. *Markdown-like syntax*: headings, lists, links, code, math.

2. *Custom directives*: block-level extensions.

```code verso
:::definition "FreyCurve" (parent := "first_reductions")
...
:::
```

3. *Custom roles*: inline extensions such as `{uses "FreyPackage"}[]`.

4. *Extensible*: directives, roles, traversals, and renderers are Lean code.

## Verso Blueprint Example

::::class "vbp-example-source"
```code verso
:::definition "FreyCurve" (parent := "first_reductions")
    (lean := "FreyPackage.freyCurve")
Uses {uses "FreyPackage"}[].
Given a Frey package $`(a,b,c,p)`, the corresponding Frey curve is the
elliptic curve over $`\Q` defined by $`Y^2 = X(X-a^p)(X+b^p)`.
:::
```
::::

{blueprint_node "FreyCurve" (siteBase := "blueprint")}

## Connecting To Lean

A mathematical object can be *connected to Lean* in several ways:

- labeled Verso inline Lean code
- compiled declarations tagged with `@[blueprint "..."]`
- existing declarations referenced by `(lean := "...")`

Example of local inline Lean code attached to a Blueprint label:

````
```lean "FreyCurve"
def FreyPackage.freyCurve (P : FreyPackage) : WeierstrassCurve ℚ := ...
```
````

Flexible model trying to be supportive of different authors' needs.

## The Graph

{blueprintGraph (view := "full") (class := "flt-graph-frame")}

# leanblueprint-to-verso

%%%
vertical := some true
%%%

*Ports existing LaTeX-based LeanBlueprint projects to Verso Blueprint.*

*Crucially relies on AI*

[https://github.com/ejgallego/leanblueprint-to-verso](https://github.com/ejgallego/leanblueprint-to-verso)

In principle, *a good fit for LLMs'* capabilities.

## leanblueprint-to-verso: Reference Blueprints

The harness was tested against four reference projects:

- [Kevin Buzzard's FLT blueprint](https://github.com/ejgallego/verso-flt)
- [Sphere Packing](https://github.com/ejgallego/verso-sphere-packing)
- [Carleson Operators on Doubling Metric Measure Spaces](https://github.com/ejgallego/verso-carleson), by Floris van Doorn
- [Noperthedron](https://github.com/ejgallego/verso-noperthedron), by David Renshaw and Jason Reed

The goal was a faithful port.

## leanblueprint-to-verso: Results And Review Harness

The naive LLM port failed in a way that *is typical* of LLMs:

::::hstack

:::vstack

- it looked plausible
- it was not faithful
- labels drifted
- structure was invented
- source correspondence was weak

Natural-language instructions alone were not enough.

The fix was a deterministic harness plus a review surface.

Review demo: [https://x80.org/flt-translation-review/](https://x80.org/flt-translation-review/)

:::

:::vstack

The harness makes translation failures visible.

```diagram (background := "#ffffff")
open Illuminate Lean in
let ah : Arrowhead := { type := .stealth }
let txt (s : String) (size : Float := 8) : Diagram SVG :=
  Diagram.text s { fontSize := size, fontFamily := "sans-serif" }
let box (name : Name) (label : String) (fill : Color) : Diagram SVG :=
  txt label
    |>.padXY 8 5
    |>.filledFrame
      (fill := fill)
      (stroke := { color := rgb!"#64748b", width := 1 })
      (cornerRadius := 4)
    |>.namedWithAnchors name
let source := box `source "source\nTeX" (rgb!"#f8fafc")
let agent := box `agent "agent\ntranslation" (rgb!"#dbeafe")
let vbp := box `vbp "VBP\nnodes" (rgb!"#dcfce7")
let structureCheck := box `structureCheck "structure\nchecks" (rgb!"#fff7ed")
let similarity := box `similarity "similarity\nchecks" (rgb!"#fff7ed")
let grounding := box `grounding "grounding\nchecks" (rgb!"#fff7ed")
let rendered := box `rendered "rendered\nreview" (rgb!"#fef9c3")
let lean := box `lean "Lean/link\nchecks" (rgb!"#fef9c3")
let audit := box `audit "human\naudit" (rgb!"#fef9c3")
Diagram.grid (hSpacing := 34) (vSpacing := 14) #[
  #[some source, none],
  #[some agent, some vbp],
  #[some structureCheck, some rendered],
  #[some similarity, some lean],
  #[some grounding, some audit]
]
  |>.connect `source.south `agent.north (arrowhead := ah)
  |>.connect `agent.east `vbp.west (arrowhead := ah)
  |>.connect `agent.south `structureCheck.north (arrowhead := ah)
  |>.connect `structureCheck.south `similarity.north (arrowhead := ah)
  |>.connect `similarity.south `grounding.north (arrowhead := ah)
  |>.connect
    { point := `grounding.west, angle := some pi, pull := 0.35 }
    { point := `agent.west, angle := some (0 : Float), pull := 0.35, arrowhead := some ah }
    (stroke := { color := rgb!"#2563eb", width := 1.2 })
    (label := some { label := txt "feedback" 6, pos := 0.52, shift := ⟨-6, 0⟩, upright := true })
  |>.connect `vbp.south `rendered.north (arrowhead := ah)
  |>.connect `rendered.south `lean.north (arrowhead := ah)
  |>.connect `lean.south `audit.north (arrowhead := ah)
  |>.scale 1.35
```

Thanks to David Christiansen and Kim Morrison for suggesting this direction.

:::

::::

## Formal Frontiers: Side-By-Side Demo

[Mathlib Initiative](https://mathlib-initiative.org/) supports the scaling
infrastructure around Mathlib and research formalization.

[Formal Frontiers](https://github.com/FormalFrontier/Etingof-RepresentationTheory-draft1)
is a new project for responsible AI-based autoformalization.

::::hstack

:::vstack

- Source document, generated VBP nodes, and Lean files become one review problem.
- The review surface is a projection of the structured output.
- Demo: [https://x80.org/vbp-etingof/blueprint/source-compare.html](https://x80.org/vbp-etingof/blueprint/source-compare.html)
:::

::::

# Blueprint Nodes As Human-AI Harnesses

%%%
vertical := some true
%%%

::::hstack

:::vstack

A blueprint node is a checked work item shared by mathematicians, agents, and Lean.

- *select*: ready, blocked, next
- *ground*: statement, dependencies, source witnesses
- *attempt*: human or agent produces Lean work
- *verify*: compiler, links, structure checks
- *review*: explain the result against the node

The node is the contract between source, proof, and review.

:::

:::vstack

```diagram (background := "#ffffff")
open Illuminate Lean in
let ah : Arrowhead := { type := .stealth }
let txt (s : String) (size : Float := 8) : Diagram SVG :=
  Diagram.text s { fontSize := size, fontFamily := "sans-serif" }
let box (name : Name) (label : String) (fill : Color) : Diagram SVG :=
  txt label
    |>.padXY 8 5
    |>.filledFrame
      (fill := fill)
      (stroke := { color := rgb!"#64748b", width := 1 })
      (cornerRadius := 4)
    |>.namedWithAnchors name
let source := box `source "mathematical\nsource" (rgb!"#f8fafc")
let node := box `node "checked\nblueprint node" (rgb!"#dcfce7")
let review := box `review "human\nreview" (rgb!"#fff7ed")
let queue := box `queue "human / agent\nwork queue" (rgb!"#fef9c3")
let lean := box `lean "Lean\ndeclaration" (rgb!"#dbeafe")
let compiler := box `compiler "compiler\nfeedback" (rgb!"#e0f2fe")
Diagram.grid (hSpacing := 30) (vSpacing := 15) #[
  #[none, some source, none],
  #[none, some node, some review],
  #[none, some queue, some lean],
  #[none, some compiler, none]
]
  |>.connect `source.south `node.north (arrowhead := ah)
  |>.connect `review.west `node.east (arrowhead := ah)
  |>.connect `node.south `queue.north (arrowhead := ah)
  |>.connect `queue.east `lean.west (arrowhead := ah)
  |>.connect `lean.south `compiler.east (arrowhead := ah)
  |>.connect `compiler.north `queue.south (arrowhead := ah)
  |>.connect `lean.north `review.south (arrowhead := ah)
  |>.scale 1.25
```

:::

::::

## What's Next

:::class "whats-next-intro"
Blueprints will help humans coordinate AI-based formalization.
:::

::::hstack

:::vstack

*Semantic interface*

In the AI era, they need to become semantic interfaces:

- readable by mathematicians
- synchronized with Lean
- structured enough for tools and agents
- reviewable after AI work

:::

:::vstack

*Engineering focus*

Near-term engineering will focus on that vision:

- stronger status semantics shared by graph, summary, and badges
- preview and metadata APIs for tools
- reliable templates and GitHub Pages workflows
- work queues and maintainer audit views
- source-compare workflows for PDF/TeX/Verso/Lean
- agent integration experiments

:::

::::

:::class "whats-next-close"
Let us know how we can help you use Verso Blueprint for *your work*!
:::

:::class "fragment fade-in thanks-overlay"
Thanks! Any Questions?
:::
